### ISSUE TITLE
Version 0.2.5a8

### ISSUE THREAD

**Issue by boboppie** [genome/pindel#14]
Dear @liangkaiye ,

Version 0.2.5a8 has been used in intansv (http://andrewhzau.github.io/intansv/) and metasv (http://bioinform.github.io/metasv/), however I can't find in it the repository, can you help?

Best wishes,
Fengyuan

**Comment by liangkaiye** [comment]
The Pindel official repository is at https://github.com/genome/pindel

**Comment by boboppie** [comment]
Hi @liangkaiye ,

Thanks. But 0.2.5a8 is not on the release page - https://github.com/genome/pindel/releases

Best wishes,
Fengyuan

**Comment by EWLameijer** [comment]
Hi Fengyuan,

My name is Eric-Wubbo Lameijer, I usually focus on the Pindel2vcf. However, I hope that you and Kai don't mind me intervening in this discussion.

As far as I can gather, version 0.2.5.a8 is the release at (or any release after) October 14, 2014. See

https://github.com/genome/pindel/commits/master 

at the header

Commits on Oct 14, 2014




  
    
    
    
  
  
    
        remove one bug in GetRealStart4Deletion, updated version number

    
    

    
        liangkaiye
       authored on Oct 14, 2014



    

  
Unfortunately, as the version number has not been updated since, the 0.2.5.a8 version used could in theory be any of the 4 updates since. However, since most updates just modified pindel2vcf or are very recent/experimental/not fully implemented yet, I think that that October 14, 2014 commit would be the one you are looking for, at 

https://github.com/genome/pindel/tree/453782df16c63f8aaff2d383a49b3fffda24110c

I hope this helps!

Best wishes,

Eric-Wubbo


Date: Tue, 12 May 2015 08:08:36 -0700

**Comment by boboppie** [comment]
Dear Eric-Wubbo,

Thank you very much for the information! I'll check out that commit.

Best wishes,
Fengyuan
