### ISSUE TITLE
Small Test deprication

### ISSUE THREAD

**Issue by thebioengineer** [genome/pindel#56]
Are the results in the Small Test outdated? I am getting different results when I am running the commands inside the make file than are output into the TargetOutput file. If the results are no longer accurate, if you could make note of that, it would be appreciated.

https://github.com/genome/pindel/tree/master/test/SmallTest

However, when I run the commands and compare the results from the devtools run_regressiontests.sh, it matches.

**Comment by EWLameijer** [comment]
Hi, thank you very much for your comment!

The test makefiles were made for a Pindel refactoring project quite some time ago, but we indeed haven't been vigilant in keeping them updated. For a part also because some of the features that were important for refactoring (maintaining Pindel's speed, for example) became less applicable when features needed to be added. 

Since I want to be sure that any code cleaning I do will not break anything, but my Makefile expertise is (still) rather lowish, I've added the run_regressiontests during one of my 'code spring cleaning' rounds, and will try to keep it updated. I've created a branch that removed the test Makefiles to avoid future confusion, and unless there appear strong arguments for keeping the test Makefiles, I'll probably remove them in a few days.

And thank you for pointing us towards this issue, this may prevent future confusion by other users!

Best regards,

Eric-Wubbo

**Comment by EWLameijer** [comment]
Anyway, as no urgent requests to keep the test Makefiles have been forthcoming, I've removed the test Makefiles to avoid future confusion. Thebioengineer, thank you for bringing up this issue! If there are further issues, please let me know. For now, I think this issue can be closed.
