### ISSUE TITLE
missed supporting reads

### ISSUE THREAD

**Issue by helloeoh001** [genome/pindel#88]
Hello,

I'm using pindel to detect tandem duplication frequently occurring in FLT3 gene in leukemia.

The size of duplicated sequence in my data is about 60bp, and the number of supporting read was about 140 when checking the bam file with IGH viewer.

However, only 90 of the them were detected by pindel, and most of the supporting reads on the left side were missed (refer to the figure below).

I need correct number of supporting reads to calculate VAF.

Please help me~

Thanks in advance

![image](https://user-images.githubusercontent.com/16658129/38807046-36749a74-41b6-11e8-86af-49329d5c82ac.png)

**Comment by liangkaiye** [comment]
Is it possible to share the local bam file to look into this?

Kaiye@xjtu.edu.cn<mailto:Kaiye@xjtu.edu.cn>



Hello,

I'm using pindel to detect tandem duplication frequently occurring in FLT3 gene in leukemia.

The size of duplicated sequence in my data is about 60bp, and the number of supporting read was about 140 when checking the bam file with IGH viewer.

However, only 90 of the them were detected by pindel, and most of the supporting reads on the left side were missed (refer to the figure below).

I need correct number of supporting reads to calculate VAF.

Please help me~

Thanks in advance

[image]<https://user-images.githubusercontent.com/16658129/38807046-36749a74-41b6-11e8-86af-49329d5c82ac.png>

**Comment by philip-holmgren** [comment]
Hi,

I think this is related to the issue I raised (https://github.com/genome/pindel/issues/86).

In that case the reason why the left reads were 'missed' is because they are used as the 'mapped' read  to find the 'unmapped' read which would be the right read of the pair (using 'mapped' and 'unmapped' here in reference to the description of the Pindel algorithm).

As far as I know the 'mapped' read is **never** taken into account for Pindel's VAF calculation although it's quite possible that read also contains the ITD and is softclipped.

**Comment by helloeoh001** [comment]
Dr. Ye,

I e-mailed you with the link that the bam file can be downloaded.

If there are any troubles in downloading, let me know.

**Comment by liangkaiye** [comment]
Got the files. I am currently working on a proposal and will start to work on the code after that.



Closed #88<https://github.com/genome/pindel/issues/88>.
